import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Image as ImageIcon, Video, Layers } from "lucide-react";
export const GlobalCreateModal = ({ isOpen, onClose, openCreateStatus, openCreateReel }) => {
    return (_jsx(AnimatePresence, { children: isOpen && (_jsxs("div", { className: "fixed inset-0 z-[200] flex items-end sm:items-center justify-center p-4", children: [_jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, onClick: onClose, className: "absolute inset-0 bg-black/80 backdrop-blur-sm" }), _jsxs(motion.div, { initial: { y: "100%", opacity: 0 }, animate: { y: 0, opacity: 1 }, exit: { y: "100%", opacity: 0 }, transition: { type: "spring", damping: 25, stiffness: 300 }, className: "relative w-full max-w-md bg-[#111114] border border-white/10 rounded-[2.5rem] p-6 shadow-2xl", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("h2", { className: "font-serif text-2xl text-white", children: "Create" }), _jsx("button", { onClick: onClose, className: "p-2 bg-white/5 rounded-full text-zinc-400 hover:text-white transition-colors", children: _jsx(X, { size: 20 }) })] }), _jsxs("div", { className: "grid grid-cols-1 gap-3", children: [_jsxs("button", { onClick: () => {
                                        onClose();
                                        openCreateStatus();
                                    }, className: "flex items-center gap-4 p-4 rounded-2xl bg-white/5 border border-white/5 hover:bg-white/10 transition-colors text-left", children: [_jsx("div", { className: "w-12 h-12 rounded-xl bg-primary/20 flex items-center justify-center", children: _jsx(Layers, { className: "text-primary", size: 24 }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-white font-bold text-lg", children: "Story" }), _jsx("p", { className: "text-zinc-500 text-xs font-medium", children: "Share a photo or text to your status" })] })] }), _jsxs("button", { onClick: () => {
                                        onClose();
                                        openCreateReel();
                                    }, className: "flex items-center gap-4 p-4 rounded-2xl bg-white/5 border border-white/5 hover:bg-white/10 transition-colors text-left", children: [_jsx("div", { className: "w-12 h-12 rounded-xl bg-accent/20 flex items-center justify-center", children: _jsx(Video, { className: "text-accent", size: 24 }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-white font-bold text-lg", children: "Discover Reel" }), _jsx("p", { className: "text-zinc-500 text-xs font-medium", children: "Post a short video to Discover" })] })] }), _jsxs("button", { onClick: () => {
                                        onClose();
                                        // We can scroll to top of feed where CreatePost is, or trigger an event.
                                        window.dispatchEvent(new Event("gounion-focus-create-post"));
                                    }, className: "flex items-center gap-4 p-4 rounded-2xl bg-white/5 border border-white/5 hover:bg-white/10 transition-colors text-left", children: [_jsx("div", { className: "w-12 h-12 rounded-xl bg-blue-500/20 flex items-center justify-center", children: _jsx(ImageIcon, { className: "text-blue-500", size: 24 }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-white font-bold text-lg", children: "Feed Post" }), _jsx("p", { className: "text-zinc-500 text-xs font-medium", children: "Share something with your followers" })] })] })] })] })] })) }));
};
